baseURL = 'https://zolletta.org/'
languageCode = 'en-us'
title = "Zolletta's Digital Garden"

theme = "kawaii"

enableEmoji = true

[pagination]
pagerSize = 6

[build]
writeStats = true

[params]
description = "The place to learn in public"
author = "Veronica Bolognesi"
theme_toggle = true
search = true
favicon = "/favicon.ico"
hero_cta = "Read my book summaries"
hero_cta_link = "/books"
copyright = "Zolletta's Digital Garden"

[[params.social]]
name = "github"
url = "https://github.com/Zolletta"

[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/veronicabolognesi/"

[[params.footer_links]]
name = "Documentation"
url = "https://github.com/yuis-ice/hugo-kawaii#readme"

[[params.footer_links]]
name = "Download"
url = "https://github.com/yuis-ice/hugo-kawaii"

  
[[params.featured_sections]]
title = "Book summaries"
description = "The books I am interested about don't age because they don't talk about the next big thing, but of foundational subjects."
icon = "âœ¨"
link = "/books"


[menu]
[[menu.main]]
name = "Home"
url = "/"
weight = 10

[[menu.main]]
name = "Books"
url = "/books"
weight = 20

[markup]
[markup.highlight]
style = "github"
noClasses = false
lineNos = true
lineNumbersInTable = false
codeFences = true
guessSyntax = true

[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[outputs]
home = ["HTML", "RSS", "JSON"]
page = ["HTML"]
section = ["HTML", "RSS"]

